# Generated by Django 6.1 on 2026-08-28 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_deleted_at_remove_user_deleted_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("token", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                ("steps_to_reproduce", models.CharField(max_length=150)),
                ("actual_behavior", models.CharField(max_length=150)),
                (
                    "type_of_feedback",
                    models.CharField(
                        choices=[
                            ("BUG REPORT", "Bug Report"),
                            ("FEATURE REQUEST", "Feature Request"),
                            ("DOCUMENTATION", "Documentation"),
                            ("USER EXPERIENCE", "User Experience"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=50,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
