# Generated by Django 6.1 on 2026-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="token",
        ),
        migrations.AddField(
            model_name="feedback",
            name="ticket",
            field=models.CharField(
                db_index=True, default=1, max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
