# Generated by Django 6.1 on 2026-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_feedback_token_feedback_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="actual_behavior",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="steps_to_reproduce",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
