# Generated by Django 6.1 on 2026-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_alter_fields_generator_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="delete_method",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resources",
            name="get_method",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resources",
            name="post_method",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resources",
            name="put_method",
            field=models.BooleanField(default=False),
        ),
    ]
