# Generated by Django 6.1 on 2026-08-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_resources_delete_method_resources_get_method_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resources",
            old_name="put_method",
            new_name="patch_method",
        ),
    ]
