# Generated by Django 6.1 on 2026-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_rename_put_method_resources_patch_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="get_method",
            field=models.BooleanField(default=True),
        ),
    ]
